version: '3'
services:
  app:
    build: ./infra
    image: app-img
    container_name: app
    ports:
      - 80:80
    volumes:
      - /vagrant:/sample
    restart: always
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - db-vol:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: sample
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
volumes:
  db-vol:
